### ISSUE TITLE
Plagiarism

### ISSUE THREAD

**Issue by falvarez1** [itsmiracler/Practical-CleanArchitecture#1]
Why are you plagiarizing other people's work?!  You even changed the commit attributions from other people to pass off as your own. This is really low.  You seem to have done that for all of the repos you claim are your own.  You even faked the profile.  This is appalling!

Here's the official source for this repo:
https://github.com/phongnguyend/Practical.CleanArchitecture

**Comment by Hona** [comment]
@itsmiracler hope you're not trying to pass this off as something you've worked on, for sake of being hired. Quite disguisting behavior.
